[package]
name = "vpnclient"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
get-last-error = "0.1.1"
openssl = "0.10.45"
qprov = { version = "0.1.0", path = "../qprov" }
winapi = { version = "0.3.9", features = ["wininet", "netioapi", "impl-default"] }
wintun = "0.2.1"

[profile.dev.package."qprov"]
opt-level = 2
